### ISSUE TITLE
Explore use of Namespaced File Capabilities to support rootless on NFS/GPFS

### ISSUE THREAD

**Issue by brianv0** [containers/storage#539] opened 2020-02-26 13:46 UTC
Linux 4.14 added "Namespaced File Capabilities"

The patch is described here:
https://github.com/torvalds/linux/commit/8db6c34f1dbc8e06aa016a9b829b06902c3e1340
http://man7.org/linux/man-pages/man7/capabilities.7.html

It seems to me that this feature could be used to support rootless containers over NFS and GPFS or similar file systems, as the file is still stored as the user's UID, but the namespaced UID is stored in an extended attribute.

> If a task writes a v3 security.capability, then it can provide a uid for
the xattr so long as the uid is valid in its own user namespace, and it
is privileged with CAP_SETFCAP over its namespace.  The kernel will
translate that rootid to an absolute uid, and write that to disk.  After
this, a task in the writer's namespace will not be able to use those
capabilities (unless rootid was 0), but a task in a namespace where the
given uid is root will.

So, during a write, the uid for the xattr is the user namespace PID - the one GPFS/NFS doesn't like, and the translated one is that of the the user executing the rootless container.

It would appear that this could resolve the more general case from containers/libpod#4551, although I note that specific issue may be resolved soon thanks to #529.

**Comment by vrothberg** [comment] 2020-03-02 09:33
@giuseppe WDYT?

**Comment by rhatdan** [comment] 2020-03-02 21:44
I don't think this has anything to do with NFS and potentially GPFS issues.
The problem is NFS is enforcing DAC_OVERRIDE and DAC_CHOWN on the server side.  If I have a process running as root inside of my user namespace, and this processes chowns a file to a different UID. Then the NFS server sees this as UID=1000 is attempting to change ownership of a file to UID 100000, and blocks it.  Since NFS Server does not know that UID=1000 is root inside of a user namespace that includes UID 100000, and it has DAC_OVERRIDE and DAC_CHOWN for the user namespace, it does not allow the access.

**Comment by giuseppe** [comment] 2020-03-03 11:14
yes, I agree with Dan.  Unfortunately this won't solve the NFS/GPFS use case.

I am going to close it, please add more comments if necessary

**Closed by giuseppe** 2020-03-03 11:14 UTC
