### ISSUE TITLE
opencontainers/runc v1.0.0-rc91 doesn't have GetClockTicks used by containerd v1.3.2

### ISSUE THREAD

**Issue by thaney071** [containers/storage#736] opened 2020-10-06 22:17 UTC
While trying to use the image.Copy method provided by https://github.com/containers/image that this tool used, I kept getting an error that GetClockTicks is undefined. I don't know how this tool or the image.Copy code is working when the versions don't align with the required methods.

 I had to add 
`replace github.com/opencontainers/runc v1.0.0-rc91 => github.com/opencontainers/runc v0.1.1`
to my go.mod file to force it to use the correct version of opencontainers/runc

**Comment by mtrmac** [comment] 2020-10-07 11:51
Skopeo is a final command, not a library; did you mean to file this against containers/image? Either way, the dependency actually comes from the containers/storage project (c/storage/pkg/archive requires github.com/opencontainers/runc/libcontainer/system ).

I imagine reverting to a **4 years old** version is not an option, and even reverting to May 2020 would not be attractive. But there may be something else c/storage can do.

**Comment by rhatdan** [comment] 2020-10-07 17:42
@thaney071 What platform are you building this on?

**Comment by mtrmac** [comment] 2020-10-08 13:04
BTW it may be possible to use c/image/copy.Image without directly depending on c/image/storage , by not using `alltransports.ParseImageName`, but directly a `NewReference` or `ParseReference` method or function of the relevant transport subpackage (e.g. `c/image/docker.NewReference`) — but I haven’t checked whether removing the direct reference also drops the versioning conflict, from the point of Go modules.

**Comment by thaney071** [comment] 2020-10-08 15:50
@rhatdan 

My go env is 
`go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/vscode/.cache/go-build"
GOENV="/home/vscode/.config/go/env"
GOEXE=""
GOFLAGS="-tags=containers_image_openpgp"
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY="bitbucket.metro.ad.selinc.com/*"
GONOSUMDB="bitbucket.metro.ad.selinc.com/*"
GOOS="linux"
GOPATH="/go"
GOPRIVATE="bitbucket.metro.ad.selinc.com/*"
GOPROXY="https://artifactory.metro.ad.selinc.com/api/go/sel-go"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/workspace/duffle-wrapper/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build467427934=/tmp/go-build -gno-record-gcc-switches"`

using `go version 1.14`

my os info is
`
vscode@553d526e0b49:/workspace/duffle-wrapper$ lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 10 (buster)
Release:        10
Codename:       buster
`

For now I have it working by just adding the `replace` command to my go mod file to force it to use the correct version.  

I should point out I am not using skopeo. I am trying to use copy.Image in my own project.

**Comment by rhatdan** [comment] 2020-10-08 18:09
Ok so why is this an issue with the upstream project?

**Comment by kolyshkin** [comment] 2020-10-29 09:35
This is between runc and containerd, not sure why the issue is filed against to this repo.

@thaney071 please take a look at https://github.com/opencontainers/runc/pull/2377/commits/402d645c5c642a4965439a156181cff3fc2f3817 as to why GetClockTicks was removed.

Now, neither containers/storage nor containers/image uses that. containerd (which you mention in the title) did, but that was changed in https://github.com/containerd/containerd/pull/4227/commits/37c839e5944eafc4c462721fc45c91d0a34e4e0e and released in containerd v1.4.1.

In any case, nothing of that is related to this repo.

**Comment by kolyshkin** [comment] 2020-10-29 09:35
@rhatdan this should be closed.

**Comment by mtrmac** [comment] 2020-10-29 15:01
> This is between runc and containerd, not sure why the issue is filed against to this repo.

https://github.com/containers/storage/issues/736#issuecomment-704882746

**Closed** 2020-10-29 18:55 UTC
Labels: kind/bug
